module_names = [
            'accenture',
            'agilefreaks',
            'autototal',
            'azets',
            'azur',
            'bitpanda',
            'bunge',
            'c4media',
            'canamgroup',
            'catena',
            'centric',
            'corteva',
            'egger',
            'emia',
            'fieldcore',
            'genos',
            'hosterion',
            'lugera',
            'toptech',
            'yopeso',
            # Add more module names as needed
            ]
